### ISSUE TITLE
No module named 'utils'

### ISSUE THREAD

**Issue by Xaffle** [tobegit3hub/tfmodel#1]
hello, tobe, 
while the tfmodel was installed successed using pip, the tfmodel command cannot be executed, the error infomation is:
Traceback (most recent call last):
  File "c:\users\###\appdata\local\continuum\anaconda3\envs\tfmodel\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\###\appdata\local\continuum\anaconda3\envs\tfmodel\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\###\AppData\Local\Continuum\anaconda3\envs\tfmodel\Scripts\tfmodel.exe\__main__.py", line 5, in <module>
  File "c:\users\###\appdata\local\continuum\anaconda3\envs\tfmodel\lib\site-packages\tfmodel\command.py", line 24, in <module>
    from tfmodel.savedmodel_analyst import SavedmodelAnalyst
  File "c:\users\###\appdata\local\continuum\anaconda3\envs\tfmodel\lib\site-packages\tfmodel\savedmodel_analyst.py", line 7, in <module>
    from utils import ModelUtil
ModuleNotFoundError: No module named 'utils'

**Comment by tobegit3hub** [comment]
It seems to be the issue about compatibility of Python 3. We will test and try to fix that soon.

**Comment by lovepocky** [comment]
https://github.com/tobegit3hub/tfmodel/blob/b57a3b765ff697bb767a5af54d1a33e9b2f56781/tfmodel/savedmodel_analyst.py#L8

edit above line to
```diff
- from utils import ModelUtil
+ from .utils import ModelUtil
```
